### ISSUE TITLE
Cs:s, doesn't work as of 04/05/2024

### ISSUE THREAD

**Issue by AwertaDreams** [0x00000ED/-CS-Source-FIX-Host_Error-CL_PreserveExistingEntity#2]
This issue bugged me for a lot of time. Thank you dude. I own you a beer.
But i have a slight issue.
It still persists

Host_Error: CL_CopyExistingEntity: missing client entity 82.

**Comment by 0x00000ED** [comment]
This fix for latest steam version CS:S and CL_CopyExistingEntity it doesn't fix it. What version do you have?

**Comment by AwertaDreams** [comment]
> This fix for latest steam version CS:S and CL_CopyExistingEntity it doesn't fix it. What version do you have?
```
Build Label:           6630498   # Uniquely identifies each build
Network PatchVersion:  6630498   # Determines client and server compatibility
Protocol version:           24   # High level network protocol version
Server version:        6630498
Server AppID:           232330
Client version:        6630498
Client AppID:              240
```

**Comment by 0x00000ED** [comment]
Do all your demos end with this error?
if yes, I can try to fix it, for this I need a demo and a map.

**Comment by AwertaDreams** [comment]
> Do all your demos end with this error? if yes, I can try to fix it, for this I need a demo and a map.

Yes, most of them. I'll provide the demo file in a second. the map is de_nuke

**Comment by AwertaDreams** [comment]
Okay - nevermind i lost the demo file.
